### ISSUE TITLE
Add UIControl rx_subscribeEnabledTo

### ISSUE THREAD

**Issue by ashfurrow** [kzaher/RxSwift#34]
Hey!

Preparing my talk for AltConf tomorrow on FRP, and I'm using RxSwift (ssssshhhhhhh don't tell anyone – I want to focus on concepts and ideas instead of "which FRP framework" I use). 

Anyway, coming from ReactiveCocoa, there are a few things I've noticed we could add. I'm making implementations for them in the sample code _for now_, but when I have time, I'll add tests and send a PR for them. 

The first one is adding `rx_subscribeEnabledTo` for `UIControl`. Something like

```swift
emailTextField.rx_text
    >- map { $0.isEmail() }
    >- submitButton.rx_subscribeEnabledTo
    >- disposeBag.addDisposable
```

**Comment by kzaher** [comment]
Hi Ash,

Yeah, I think there were a lot of requests for that. I think this is a good idea, so if you want to do a PR, that would be great. 

I think I've seen @dtartaglia  also like this :)

:+1:
