### ISSUE TITLE
Box class will must to be independant

### ISSUE THREAD

**Issue by carlosypunto** [kzaher/RxSwift#4]
Can you use https://github.com/robrix/Box?

**Comment by kzaher** [comment]
Hi, sorry for late reply. 
You are correct. Using my own box is probably not the best choice.
The same is valid for error monad.
I'm thinking about using https://github.com/antitypical/Result and https://github.com/robrix/Box and bumping the version to 2.0.
I would also like to make the code more standardized so new users aren't worried about what does >==, or >>! mean.
Any feedback on this would be appreciated.

**Comment by carlosypunto** [comment]
I do not know if there is a radar. But the bug is known by anybody.

**Comment by kzaher** [comment]
I'm also interested are there any other suggestions for error monad and box.

**Comment by carlosypunto** [comment]
* the .Failure case of antitypical/Result is generic type, it isn't of NSError concrete type, I see better. Maybe, you can rename your Result to RxResult, what you think?
* robrix/Box I see fine

**Comment by kzaher** [comment]
Renamed Box and Result to RxBox and RxResult.
