### ISSUE TITLE
Doc / Example: Converting callback function to RxSwift

### ISSUE THREAD

**Issue by tp** [kzaher/RxSwift#43]
Hi,

when evaluating RxSwift, I was unable to find a practical example to convert a callback-style API to RxSwift.

How would one wrap this with RxSwift for example:

```
    func add(a: Int64, _ b: Int64, cb: (Int64) -> ()) {
        cb(a+b)
    }
```

Would for example returning an `Observable<Int64>` be the best choice, or are there specific options for returning only a single value?

Thanks for your help!

**Comment by alcarvalho** [comment]
I would use an `Observable<Int64>` indeed.

In this particular case, where you have no async code, you could just write:

```swift
func add(a: Int64, _ b: Int64) -> Observable<Int64> {
  return just(a + b)
}
```

But since we generally use callbacks for async cases, this is a more complete version:

```swift
func add(a: Int64, _ b: Int64) -> Observable<Int64> {
  return AnonymousObservable { observer in 
    sendNext(observer, a + b)
    sendCompleted(observer)
    return AnonymousDisposable {
      // do any clean up needed on unsubscribe
    }
  }
}
```

**Comment by kzaher** [comment]
Hi,

there are examples in RxCocoa project how to wrap callback APIs.

https://github.com/kzaher/RxSwift/blob/master/RxCocoa/RxCocoa/Common/NSURLSession%2BRx.swift

For example wrapping `NSURLSession.dataTaskWithRequest`

```
public func rx_response(request: NSURLRequest) -> Observable<(NSData!, NSURLResponse!)> {
        return create { observer in
                let task = self.dataTaskWithRequest(request) { (data, response, error) in  
                if data == nil || response == nil {
                    sendError(observer, error ?? UnknownError)
                }
                else {
                    sendNext(observer, (data, response))
                    sendCompleted(observer)
                }
            }
            
            task.resume()
                
            return AnonymousDisposable {
                task.cancel()
            }
        }
    }
```

Kruno

**Comment by tp** [comment]
Missed that one, thanks a lot :+1:
