### ISSUE TITLE
Architecture Error when debuggingin on iPod Touch Device

### ISSUE THREAD

**Issue by mbalex99** [kzaher/RxSwift#53]
dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
          Referenced from: /private/var/mobile/Containers/Bundle/Application/5CF8EAE4-E014-44DE-878F-E5C17DB1B19F/Eden.app/Eden
          Reason: no suitable image found.  Did find:
	  /private/var/mobile/Containers/Bundle/Application/5CF8EAE4-E014-44DE-878F-E5C17DB1B19F/Eden.app/Frameworks/RxSwift.framework/RxSwift: mach-o, but wrong architecture
	  /private/var/mobile/Containers/Bundle/Application/5CF8EAE4-E014-44DE-878F-E5C17DB1B19F/Eden.app/Frameworks/RxSwift.framework/RxSwift: mach-o, but wrong architecture

So strange... It works completely fine on my iPhone 6 and iPads

**Comment by kzaher** [comment]
Hi Maximilian,

Can you tell me what method did you use to build RXS? Manual or CocoaPods?

I'm assuming this has something with architectures that you are using in Xcode to build RXS.

Build > Valid Architectures

Is iPod architecture on that list?

**Comment by kzaher** [comment]
Hi Maximilian, any news on this?

I think I've seen some comments in Slack that you'we fixed that, but not sure :)

**Comment by kzaher** [comment]
Hi @mbalex99,

I'm doing a post release sweep of resolved issues, I can't figure out is yours solved or are you still having issues with it.

Please let me know so I know what to do with it.
