### ISSUE TITLE
Observe typealiases properties

### ISSUE THREAD

**Issue by tp** [kzaher/RxSwift#56]
I wanted to use RxCocoa to observes a views bounds like this:

```swift
        let obs : Observable<CGRect?> = nibView.rx_observe("bounds")
        obs >- subscribeNext {
            bounds in
            println(bounds)
        }
```
But then `bounds` is always `nil`.

When I change it to this:

```swift
        let obs : Observable<AnyObject?> = nibView.rx_observe("bounds")
        obs >- subscribeNext {
            bounds in
            println(bounds)
        }
```

bounds is actually an `Optional(NSRect: {{0, 0}, {768, 43.5}})`.

I can't seems to access the NSRect type in my iOS project (even though I import Foundation), and since it is only a type alias for CGRect, I thought maybe this code should work with `CGRect?` like in the first snippet?

Thanks for your suggestions.

**Comment by kzaher** [comment]
It's funny, but I've written unit test about that case yesterday.

```
func testObserveWeak_ObserveCGRect() {
        var root: HasStrongProperty! = HasStrongProperty()
        
        let latest = RxMutableBox<CGRect?>(nil)
        
        XCTAssertTrue(latest.value == nil)
        
        root.rx_observeWeakly("frame")
            >- subscribeNext { (n: NSValue?) in
                if let n = n {
                    var frameValue = CGRect(x: 0, y: 0, width: 0, height: 0)
                    n.getValue(&frameValue)
                    latest.value = frameValue
                }
                else {
                    latest.value = nil
                }
            }
     ...
```

`CGRect` becomes in KVO world `NSValue`, and it's not `CGRect`, so that's why it's `nil`.

Having said that, I think I can actually improve this and internally unwrap `CGRect` and `CGPoint` so it should work when you do

```
nibView.rx_observe("bounds") as Observable<CGRect?>
        obs >- subscribeNext { bounds in
            println(bounds)
        }
```

Just didn't came to my attention :)

Let me know does that work.

I think I know a way to improve this for next release, but I will need to investigate more.

**Comment by kzaher** [comment]
Also, be careful, I think `UIView` classes aren't officially KVO compliant, but on the other hand, I doubt `Apple` will ever make them not compliant :p

**Comment by kzaher** [comment]
I've added official support for observing `CGRect`, `CGSize` and `CGPoint`. There are specializations that handle those cases.

It's even documented now :)

https://github.com/kzaher/RxSwift/blob/master/Documentation/GettingStarted.md#observing-structs

Closing this issue, let me know if you have any further problems.
