### ISSUE TITLE
Question: Create Observable and corresponding Observer at the same time

### ISSUE THREAD

**Issue by tp** [kzaher/RxSwift#57]
I have a class that implements a delegate protocol for a custom DatePicker which gets called whenever the selected date changes.

Now I want to expose the current date as an `Observable`.

With ReactiveCocoa I created a Signal and Sink in the constructor, exposing the Signal to the outside and keeping the Sink private to publish new values.

The closest I came with RxSwift was creating a `PublishSubject` which I exposed as `Observable` and also kept internally to `sendNext` new values.

Is this the best approach? I would rather just expose a pure Observable, such that clients can not type-cast back to a `PublishSubject` and start sending values (though this is only a theoretical problem).

**Comment by kzaher** [comment]
Hi,

regarding wrapping delegates, RXS has generic delegate wrapping functionality.

This is how we wrapped UISearchBar in RxCocoa

```
class RxSearchBarDelegateProxy : DelegateProxy
                               , UISearchBarDelegate
                               , DelegateProxyType {
    
    class func currentDelegateFor(object: AnyObject) -> AnyObject? {
        let searchBar: UISearchBar = castOrFatalError(object)
        return searchBar.delegate
    }
    
    class func setCurrentDelegate(delegate: AnyObject?, toObject object: AnyObject) {
        let searchBar: UISearchBar = castOrFatalError(object)
        searchBar.delegate = castOptionalOrFatalError(delegate)
    }
}
```

```
extension UISearchBar {
    
    public var rx_delegate: DelegateProxy {
        return proxyForObject(self) as RxSearchBarDelegateProxy
    }
    
    public var rx_searchText: Observable<String> {
        return defer { [weak self] in
            let text = self?.text ?? ""
            
            return self?.rx_delegate.observe("searchBar:textDidChange:") ?? empty()
                    >- map { a in
                        return a[1] as? String ?? ""
                    }
                    >- startWith(text)
        }
    }
}
```

If you want to hide type of any observable, you can use `asObservable` operator.

```
return original
     >- asObservable
```

Hope this helps.
