### ISSUE TITLE
Obstacle to learning RxSwift: "No such module 'RxSwift'" in example playgrounds

### ISSUE THREAD

**Issue by clozach** [kzaher/RxSwift#58]
In order to learn RxSwift by example, I launched Rx.xcworkspace and clicked on Introduction.playground. Line 2 immediately came up with the error: No such module 'RxSwift'. The same happens if I open the playground (or any of the playgrounds in Playgrounds/ObservablesOperators).

Am I missing a step? Is this known to be broken?

Fwiw, this is in Xcode Version 6.4 (6E35b).

**Comment by carlosypunto** [comment]
Hi @clozach 

For the playgrounds work, you need build the library before.

1.- Select RxSwift-OSX Scheme
2.- Select Product -> Build menu or Command+B

Then playgrounds must work

**Comment by kzaher** [comment]
We'll add instructions to playgrounds, so it will be clearer in future.

**Comment by clozach** [comment]
Thanks!

**Comment by paddlefish** [comment]
This error will also occur if you have the Xcode -> Preferences -> Locations -> Derived Data [ Advanced... button ] -> Build Location = Legacy.

To fix it choose Build Location: Unique (which I think is the default).

**Comment by XueSeason** [comment]
good job! Thx.

**Comment by PrajeetShrestha** [comment]
Hi, I tried to integrate Playgrounds and tried to tested playground inside workspace made my cocoapods. But it shows these errors. Any idea? 
![image](https://user-images.githubusercontent.com/8730910/26920868-0a1be614-4c5a-11e7-918b-cb30b5e985aa.png)

**Comment by sergdort** [comment]
Hi, @PrajeetShrestha  did you build `RxSwift-MaOS` target before?

**Comment by PrajeetShrestha** [comment]
Hi Sergdort. As I mentioned. It is not this repo that I cloned. But I am integrating RxSwift in my own project through cocoapods. I created playground in there as well. I am able to import RxSwift and RxCocoa in the playground file but can't use the above method.  There is no RxSwift-MacOS Target hence.

**Comment by sergdort** [comment]
Oh, sorry my bad :)

Which target contains `MyPlayground` is it `TestRx`?
If so have you build `TestRx `?

**Comment by aelam** [comment]
I cleaned the 'DerivedData', and built the RxSwift-macOS scheme, and checked that the framework is there, but in playground, it still doesn't work

**Comment by quanguyen** [comment]
Oh shoot! I just found how to fix this: selecting a simulator instead of a physical device!

![screen shot 2018-10-03 at 5 41 23 pm](https://user-images.githubusercontent.com/11938078/46405877-e1c76200-c733-11e8-979f-fbf7c4b1edec.png)


(I referenced from [this link](https://forums.raywenderlich.com/t/chapter-2-observables-project-problems/27877/22))

Regards,

**Comment by JAIRMG** [comment]
The sources folder into playground file is empty, I already deleted the derived data

**Comment by dipkasyap** [comment]
<img width="420" alt="Screen Shot 2020-07-09 at 1 44 49 pm" src="https://user-images.githubusercontent.com/12591229/86994764-94bace80-c1ea-11ea-9be8-d2bceb5e961e.png">
In my case Checking "Build Active Scheme" solved the problem.

**Comment by freak4pc** [comment]
The original thread is 5 years old and from Xcode 6.4. If someone has a modern issue with it, it would be advisable to open a new issue, so we can track it :) Thanks !
