### ISSUE TITLE
Cannot invoke 'rx_observe' with an argument list of type '(String)'

### ISSUE THREAD

**Issue by esttorhe** [kzaher/RxSwift#59]
I have a class that looks like this:
```swift
public class MyClass: NSObject {
   public var active: Bool = false
}
```

Then at some point either on the `init` or on another function I'm trying to do this:
```swift
self.rx_observe("active")
```

But it doesn't matter what parameters I pass and its labels or not I keep receiving this:
```
Cannot invoke 'rx_observe' with an argument list of type '(String)'
```

Any ideas? ¯\\\_(ツ)\_/¯

Also if I try to access `KVOObservable` directly the compiler doesn't seem to find it :/

___
*Edit: This is on the `feature/swift2.0` branch*

**Comment by kzaher** [comment]
Hi,

so a couple of things. KVO is an objc mechanism, so to support it you need to declare property as 
```
dynamic var active: Bool = false
```

compiler needs to know type of thing that you are observing, and type is contained in observable return value, so you would need to do something like 
```
self.rx_observe("active") as Observable<NSNumber?> // KVO doesn't know about bool, bool = NSNumber
```

Hope this helps.

**Comment by esttorhe** [comment]
I tried that; the only thing I did not try was adding `?` to the specific type
`<NSNumber>` != `<NSNumber?>`

Thanks
