### ISSUE TITLE
RxExample-IO 'Search Wikipedia' launch exception "attempted to retain deallocated object"

### ISSUE THREAD

**Issue by DayBit** [kzaher/RxSwift#65]
On RxExample-IOS writing text on search field of 'Search Wikipedia' launch exception "attempted to retain deallocated object".

I'm using Xcode 6.4 not 6.3.

**Comment by kzaher** [comment]
Hi,
I've released a hotfix 1.8.1 for that problem yesterday evening :) Is it still happening for you?

**Comment by DayBit** [comment]
After a 'git pull' the bug is gone.
