### ISSUE TITLE
post request

### ISSUE THREAD

**Issue by croccio** [kzaher/RxSwift#68]
how can i do rest post request? thank you

i'm new in rx

**Comment by kzaher** [comment]
Hi,

you first need build `NSURLRequest` that describes the URL request.

You can do something like [http://stackoverflow.com/a/6149088](http://stackoverflow.com/a/6149088)

After that you use one of the 
* `rx_rx_response`
* `rx_data`
* `rx_JSON`

depending on what are you interested on accessing.

Hope that helps.

**Comment by croccio** [comment]
thank you very much :D i've done it but the request won't start. i've seen your example but i don't understand as it works


i've done this 


import Foundation
import RxSwift
import RxCocoa

    class PPTPasspartuAPI : PPTIPasspartuAPI{
  
      var authString : String?;
  
      init?(){}
  
      func login(username: String, password: String) -> Observable<PPTUser> {
    
        let userPasswordString = "\(username):\(password)";
        let userPasswordData = userPasswordString.dataUsingEncoding(NSUTF8StringEncoding);
        let authString = userPasswordData!.base64EncodedStringWithOptions(nil);
    
        return getUrlSession(authString).rx_JSON(getRequest(LoginService(), username))
          >- mapOrDie { jsonResult in
            return castOrFail(jsonResult).flatMap { (json: NSDictionary) in
              return PPTUser.parseJSON(json)
            }
          }
          >- observeSingleOn(doOnMainThread())
      }
    }

where with getUrlSession i get URLSession configured with Base Auth and with get request i build my request

than how can i "launch" it when i press a button? i tried with a lot of snippets, but i can't get any response. but i i use rx_response than i've got a response using subscribeNext.

**Comment by kzaher** [comment]
Hi, 
I'm not sure I understand the question :) 

So one thing you'll need to do is to subscribe to observable somewhere, and then you should get the response.

You need to use `rx_response` to get the raw status code and cast from `NSURLResposnse` to `NSURLResponse`.

Hope this helps.

**Comment by croccio** [comment]
sorry, my english isn't very good.

when i subscribe it to observable, "PPTUser.parseJSON(json)" isn't called and i don't know why :( can you show me how can i subscribe it to observable and handle object that it return or errors? for example i need to handle status http response, so for example if status is 200 parse json, if it is 304 do other thing.

**Comment by kzaher** [comment]
Hi you could use something like
```
NSURLSession.sharedSession().rx_response(yourPostRequest)
            >- debug("let's see did this thing error out") // this will print out information to console
            >- flatMap { (data, response) in
                   let httpResponse = response as! NSHTTPURLResponse
                   if httpResponse.statusCode == 304 {
                              return failWith(yourNSError)
                  }
                  //
                  return just(transform(data))
            }
            >- subscribe { event in
                    println(event) // if error happened, this will also print out error to console 
           } 
```

**Comment by croccio** [comment]
thank you very much :) i was doing it with rx_JSON but with it i can't get status code :)

**Comment by kzaher** [comment]
Does it work for you now?

**Comment by croccio** [comment]
yes it works :) thank you very much :)

**Comment by kzaher** [comment]
Cool, closing this.
