### ISSUE TITLE
listener on more view controller

### ISSUE THREAD

**Issue by croccio** [kzaher/RxSwift#73]
is there any way to get the result of subscribe in different view controller/class? for example for login i open a modal on my navigation controller. to start requst i subscribe login on modal view controller. when it finish i can get result on modalviewcontroller. how can i catch the login result on a view controller in navigation controller?

**Comment by kzaher** [comment]
I can't be sure I've understood the question correctly, but I'll try to answer it :)

When you do subscribe to an observable that represents login, you are starting login process. This library doesn't make any assumptions about implementation of `subscribeNext` block, or knows anything about view controllers.

From the way your question was asked I would assume that you have some kind of tight coupling between 2 view controllers, and that isn't a good thing using this library or not :)

**Comment by croccio** [comment]
i'll try to explain better.

can i be notified if my object PPTUser (singleton) change?

**Comment by carlosypunto** [comment]
Hi @croccio I think your singleton should have a property of type `PublishSubject`. You could suscribe to this property

**Comment by croccio** [comment]
how can i implement it? i found example on internet but they're in java :( but i think it is what i need

**Comment by carlosypunto** [comment]
```swift
let subject = PublishSubject<String>()
subject
        >- subscribeNext {
            println($0)
        }
sendNext(subject, "a")
sendNext(subject, "b")
```

**Comment by carlosypunto** [comment]
Anyway heed to kzaher over coupling. It may not be a good idea without precautions I do not know exactly you want to do

**Comment by kzaher** [comment]
@carlosypunto thnx for helping out answering.

I would just suggest using `Variable<String>` or `BehaviorSubject<String>` because they also send last/initial value, and that is probably more suitable for this purpose.

@croccio  I had wrong understanding what you were trying to do from your initial description :)

Observing logged in user sounds reasonable.

Hope this helps.

**Comment by kzaher** [comment]
http://reactivex.io/documentation/subject.html

**Comment by croccio** [comment]
thank you guys. but why if i sendError(ob, error) than when i call on next or onCompleted they're no executed?

**Comment by carlosypunto** [comment]
> By the terms of the Observable contract, it may call onNext zero or more times, and then may follow those calls with a call to either onCompleted or onError but not both, which will be its last call.

From: http://reactivex.io/documentation/observable.html

**Comment by croccio** [comment]
is there any way to re-enabled all?

**Comment by carlosypunto** [comment]
there aren't!

But, you can use an enum as the type of the Subject, for example a RxResult
https://github.com/kzaher/RxSwift/blob/master/RxSwift/RxSwift/RxResult.swift#L27

```swift
    let subject = PublishSubject<RxResult<String>>()
    subject 
        >- subscribeNext { result in
            switch result {
            case .Success(let boxedValue):
                println(boxedValue.value)
            case .Failure(let error):
                println(error.localizedDescription)
            }
        }
    sendNext(subject, RxResult.Failure(NSError(domain: "test", code: 0, userInfo: nil)))
    sendNext(subject, RxResult.Success(RxBox("a")))
    sendNext(subject, RxResult.Success(RxBox("b")))
```

**Comment by carlosypunto** [comment]
Or you can use the `catch` operator.

https://github.com/kzaher/RxSwift/blob/master/Playgrounds/ObservablesOperators/Observables%2BError%20Handling.playground/Contents.swift#L18

**Comment by kzaher** [comment]
Hi @croccio,

I'm doing a post release sweep of resolved issues, I can figure out is yours solved or are you still having issues with it.

Please let me know so I know what to do with it.

**Comment by croccio** [comment]
Sorry i've thinked i've answer you. I've solved thank you 😁

Inviato da iPhone

**Comment by kzaher** [comment]
Awesome
